<div class="row">
    <div class="col-md-12"> </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-md-12 table-widget">
                <div class="panel">
                    <div class="panel-heading">
                        <div class="panel-title"> <i class="fa fa-user"></i> Perfis </div>
                        <div class="panel pull-right" id="search-panel-user" style=" border:0px red solid;float:left">
                            <input type="text" placeholder="Pesquise pelo nome" name="search_user" id="panelSearch" style="height: 39px;float:left; margin-right: 1px;">
                            <button class="btn btn-primary btn-gradient pesPerfil" id="pesPerfil" style="float:right;height: 39px;width: 53px;">
                                <i class="glyphicons glyphicons-search"></i>
                            </button>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div role="grid" class="dataTables_wrapper form-inline" id="datatable_wrapper">
                            <div class="row">
                                <div class="col-sm-12 datatables-toolbar">
                                    <div class="pull-right"></div>
                                    <div class="pull-left"></div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                            <table id="datatable" class="table table-striped dataTable">
                                <thead>
                                    <tr role="row">
                                        <th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-sort="ascending" aria-label=": activate to sort column descending"></th>
                                        <th id="table-name" class="sorting" role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-label="User: activate to sort column ascending"> Nome </th>
                                        <th id="table-user" class="sorting" role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-label="Phone: activate to sort column ascending">Usuário</th>
                                        <th id="table-email" class="sorting" role="columnheader" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-label="Contact: activate to sort column ascending">Email</th>
                                        <th id="table-perfil" class="text-center " role="columnheader" rowspan="1" colspan="1" aria-label="Profile">Perfil</th>
                                    </tr>
                                </thead>

                                <tbody id="list_perfil_users" role="alert" aria-live="polite" aria-relevant="all">

                                </tbody>
                            </table>
                            <div class="row">
                                <div class="col-sm-12 datatables-footer">
                                    <div class="pull-left"> </div>
                                    <div class="pull-right"> </div>
                                    <div class="clearfix"> </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>
</div>

<script type="text/javascript" src="/js/home/listagem.js"></script>