<script type="text/javascript">
    var username = '<?php echo $this->username; ?>';
</script>
<form role="form" class="form-horizontal" id="formPerfil">
    <div class="col-md-3 col-lg-4">
        <div class="row">
            <div class="col-md-11">
                <div class="panel profile-panel">
                    <div class="panel-heading">
                        <div class="panel-title"> <i class="fa fa-user"></i> User Profile -</div>
                        <span class="panel-title-sm pull-left text-success" style="color: #7ec35d; padding-left: 7px; padding-top: 2px;"> Online</span>
                        <div class="panel-btns pull-right margin-left">
                            <div class="btn-group">
                                <p class="popover-demo">
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="panel-body" style="z-index: 0;">

                        <div data-name="myimage" data-provides="fileupload" class="fileupload fileupload-exists">
                            <input type="hidden" value="" name="myimage">
                            <div id="new">
                                <div id="img_profile" style="max-width: 300px; max-height: 260px; line-height: 34px;" class="fileupload-preview fileupload-exists thumbnail"> </div>
                            </div>
                        </div>
                    </div>

                    <div class="panel-footer">
                        <div class="row">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




    <div class="col-md-6">
        <div class="row">
            <div class="col-md-12">
                <div class="panel">
                    <div class="panel-heading">
                        <div class="panel-title"> <i class="fa fa-pencil"></i> Dados Perfil </div>
                    </div>
                    <div class="panel-body">

                        <div class="form-group">
                            <label class="col-lg-3 text-right"> Usuário </label>
                            <div class="col-lg-8">
                                <div id="user_result"> </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-3 text-right"> Nome </label>
                            <div class="col-lg-8">
                                <div id="name_result"> </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-3 text-right"> Estado </label>
                            <div class="col-lg-8">
                                <div id="result_uf"> </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-3 text-right"> Cidade </label>
                            <div class="col-lg-8">
                                <div id="result_cidade"> </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-3 text-right"> Email </label>
                            <div class="col-lg-8">
                                <div id="email_user"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<div id="nao_encontrado"></div>
<script type="text/javascript" src="/js/home/perfilContatos.js"></script>