<script type="text/javascript"> var lasProfile = '<?php echo $this->lastSee; ?>';</script>

<div class="row">
    <div class="col-md-5 col-lg-6">
        <div class="row">
            <div class="col-md-12">
                <div class="panel">
                    <div class="panel-heading">
                        <div class="panel-title"> <i class="fa fa-pencil"></i> Administração </div>
                        <ul id="ul-administracao" class="nav panel-tabs">
                            <li class="active"><a href="#tab1" data-toggle="tab">Mensagem</a></li>
                            <li><a href="#tab2" data-toggle="tab">Regras</a></li>
                        </ul>
                    </div>
                    <div class="panel-body padding-none margin-top-sm">
                        <div class="tab-content padding-none border-none">
                            <div id="tab1" class="tab-pane active">
                                <div class="tab-body">
                                    <div class="media margin-top-lg chat-panel">
                                        <div class="media-img pull-left"> <a href="/home/perfil/perfil/username/admin/" style="cursor: pointer;"> <img src="/img/alunos/david_rodrigues.jpg" class="img-responsive" alt="avatar" /> </a> </div>
                                        <div class="media-body">
                                            <div class="media-content">
                                                <h4 class="media-heading">Administrador</h4>
<!--                                                <p class="media-timestamp">January 12, 2013 at 1:38 pm</p>-->
                                                Tem certeza que deseja exclui a conta <strong><?php echo $this->user['user']->nomeCompleto; ?> </strong> ?. </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="panel-footer">
                                    <form class="form-horizontal margin-top" role="form" action="/home/perfil/excluir" method="POST" />
                                    <div class="form-group">
                                        <input type="hidden" name="remove" value="ok" />
                                        <div class="col-md-8">
                                            
                                        </div>
                                        <div class="col-md-2">
                                            <!--                                            <button type="button" class="btn btn-primary">Reply</button>-->
                                            <input type="submit" class="btn btn-primary" value="enviar" />
                                        </div>
                                    </div>
                                    </form>
                                </div>
                            </div>
                            <div id="tab2" class="tab-pane">
                                <div class="tab-body">
                                    <table class="table table-striped table-widget table-checklist" id="datatable_2">
                                        <thead>
                                            <tr>
                                                <th>Status</th>
                                                <th>Date</th>
                                                <th>Description</th>
                                                <th>Assigned To</th>
                                                <th>Number</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td><span class="label label-primary">PHP</span></td>
                                                <td>10/19/2013</td>
                                                <td>Develop <b>Prototype</b> for amazon matrix</td>
                                                <td>Ashley Time</td>
                                                <td><b>[#4311525]</b></td>
                                            </tr>
                                            <tr>
                                                <td><span class="label label-primary">Utility</span></td>
                                                <td>11/14/2013</td>
                                                <td>Convert Frontend to <b>Bootstrap 3</b></td>
                                                <td>Roger Wins</td>
                                                <td><b>[#1531275]</b></td>
                                            </tr>
                                            <tr>
                                                <td><span class="label label-primary">CSS</span></td>
                                                <td>01/03/2014</td>
                                                <td>Re-Style client <b>Header</b> for release</td>
                                                <td>Kevin Heart</td>
                                                <td><b>[#6233255]</b></td>
                                            </tr>
                                            <tr>
                                                <td><span class="label label-primary">HTML</span></td>
                                                <td>10/29/2013</td>
                                                <td>Create new <b>Accordion</b> for FAQ</td>
                                                <td>Jacop Parker</td>
                                                <td><b>[#5332275]</b></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<row>

    <div class="row" style="margin-top: 2%;">
        <div class="col-md-5 col-lg-5">
            <div class="row" id="loadLastPerfilResult">

            </div>
        </div>
    </div>
</row>
<script type="text/javascript" src="/js/home/home.js"></script>