
    <div class="col-md-7 col-lg-8">
        <div class="row">
            <div class="col-md-12">
                <div class="panel profile-panel">
                    <div class="panel-heading">
                        <div class="panel-title"> <i class="fa fa-user"></i> Edição do Perfil </div>
                        <span style="color: #7ec35d; padding-left: 7px; padding-top: 2px;" class="panel-title-sm pull-left text-success"> Online</span>
                        <div class="panel-btns pull-right margin-left">
                            <div class="btn-group">
                                <button data-toggle="dropdown" class="btn btn-default btn-gradient dropdown-toggle" type="button"><span class="glyphicons glyphicons-cogwheel"></span></button>
                                <ul role="menu" class="dropdown-menu checkbox-persist pull-right text-left">
                                    <li><a><i class="fa fa-envelope-o"></i> Message </a></li>
                                    <li><a><i class="fa fa-user"></i> Add Friend </a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div id="profile-avatar" class="col-xs-4"> <img width="150" height="112" alt="avatar" class="img-responsive" src="img/avatars/login.png"> </div>
                            <div class="col-xs-8">
                                <div class="profile-data">

                                    <form class="form-horizontal" role="form">
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="cp"> Username</label>
                                            <div class="col-md-10">
                                                <div class="input-group"> <span class="input-group-addon"><i class="fa fa-hand-o-right"></i> </span>
                                                    <input type="text" value="#37a8e8" placeholder="#37a8e8" id="cp" class="form-control colorpicker margin-top-none">
                                                </div>
                                            </div>
                                        </div>


                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="cp"> Password </label>
                                            <div class="col-md-10">
                                                <div class="input-group"> <span class="input-group-addon"><i class="fa fa-hand-o-right"></i> </span>
                                                    <input type="text" value="#37a8e8" placeholder="#37a8e8" id="cp" class="form-control colorpicker margin-top-none">
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="cp"> Estado </label>
                                            <div class="col-md-10">
                                                <div class="input-group"> <span class="input-group-addon"><i class="fa fa-hand-o-right"></i> </span>
                                                    <input type="text" value="#37a8e8" placeholder="#37a8e8" id="cp" class="form-control colorpicker margin-top-none">
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="cp"> Cidade </label>
                                            <div class="col-md-10">
                                                <div class="input-group"> <span class="input-group-addon"><i class="fa fa-hand-o-right"></i> </span>
                                                    <input type="text" value="#37a8e8" placeholder="#37a8e8" id="cp" class="form-control colorpicker margin-top-none">
                                                </div>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="col-lg-2 control-label" for="cp"> Email </label>
                                            <div class="col-md-10">
                                                <div class="input-group"> <span class="input-group-addon"><i class="fa fa-hand-o-right"></i> </span>
                                                    <input type="text" value="#37a8e8" placeholder="#37a8e8" id="cp" class="form-control colorpicker margin-top-none">
                                                </div>
                                            </div>
                                        </div>
                                        
                                    </form>

                                </div>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-footer">
                        <div class="row">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
