<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="pragma" content="no-cache">
        <meta http-equiv="Cache-control" content="no-cache">
        <meta http-equiv="cache-control" content="no-cache, must-revalidate">	
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php echo $this->headMeta(); ?> 
        <?php echo $this->headTitle(); ?>

        <!-- Font CSS  -->
        <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Open+Sans:400,600,700" />

        <!-- Core CSS  -->
        <link rel="stylesheet" type="text/css" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" />
        <link rel="stylesheet" type="text/css" href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" />
        <link rel="stylesheet" type="text/css" href="/fonts/glyphicons_pro/glyphicons.min.css" />


        <!-- Plugin CSS -->
        <link rel="stylesheet" type="text/css" href="/vendor/plugins/chosen/chosen.min.css" />
        <link rel="stylesheet" type="text/css" href="/vendor/plugins/timepicker/bootstrap-timepicker.min.css" />
        <link rel="stylesheet" type="text/css" href="/vendor/plugins/colorpicker/colorpicker.css" />
        <link rel="stylesheet" type="text/css" href="/vendor/plugins/datepicker/datepicker.css" />
        <link rel="stylesheet" type="text/css" href="/vendor/plugins/daterange/daterangepicker.css" />
        <link rel="stylesheet" type="text/css" href="/vendor/plugins/formswitch/css/bootstrap-switch.css" />
        <link rel="stylesheet" type="text/css" href="/vendor/plugins/tags/tagmanager.css" />

        <!-- Theme CSS -->

        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/theme.css') . "\n\r"; ?>  
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/pages.css') . "\n\r"; ?>  
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/plugins.css') . "\n\r"; ?>  
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/responsive.css') . "\n\r"; ?>  

        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/vendor/plugins/daterange/daterangepicker.css') . "\n\r"; ?>  



        <!-- Demonstration CSS -->
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/demo.css') . "\n\r"; ?>  

        <!-- Your Custom CSS -->
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/custom.css') . "\n\r"; ?>  

        <!-- Favicon -->
        <link rel="shortcut icon" href="/img/favicon.ico" />

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Core Javascript - via CDN --> 
        <script src="/js/jquery-1.10.2.js"></script> 
        <script src="/js/jquery-ui.js-1.10.3.js"></script>
        <!--<script src="/js/jquery-1.11.1.min.js"></script>--> 
        <script src="/js/bootstrap.min.js"></script> 


        <!-- Plugins --> 
        <script type="text/javascript" src="/vendor/plugins/globalize/globalize.js"></script> 
        <script type="text/javascript" src="/vendor/plugins/chosen/chosen.jquery.min.js"></script> 
        <script type="text/javascript" src="/vendor/plugins/daterange/moment.min.js"></script> 
        <script type="text/javascript" src="/vendor/plugins/colorpicker/bootstrap-colorpicker.js"></script> 
        <script type="text/javascript" src="/vendor/plugins/formswitch/js/bootstrap-switch.min.js"></script> 
        <script type="text/javascript" src="/vendor/plugins/jquerymask/jquery.maskedinput.min.js"></script> 
        <script type="text/javascript" src="/vendor/plugins/tags/tagmanager.js"></script> 

        <!-- Theme Javascript --> 
        <script type="text/javascript">
            $(document).ready(function() {
                // Init Theme Core 	  
                Core.init();
//                $('#loading').modal('show');
                $('#retorno').hide();
                $('#loading').hide();


                // init popover
                $("[data-toggle=popover]").popover({html: true})

                // popover auto close timer  
                $('.popover-demo button').on('show.bs.popover', function() {
                    var This = $(this);

                    var animate = window.setTimeout(function() {
                        $(This).popover('hide')
                    }, 4500);
                });

//                setTimeout(function() {
//                    $('#loading').modal('hide');
//                }, 600);

            });

        </script>
        <script type="text/javascript" src="/js/uniform.min.js"></script> 
        <script type="text/javascript" src="/js/main.js"></script>
        <script type="text/javascript" src="/js/custom.js"></script> 
    </head>
    <body class="fixed-breadcrumbs sidebar-collapsed">
        <!--	<div id="loading"></div>-->
        <div class="modal fade" id="loading" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <!--<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>-->
                        <h4 class="modal-title">CARREGANDO</h4>
                    </div>
                    <div class="modal-body">
                        <div class="alert">
                            <img src="/img/loadings/ajax-loader.gif">
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <!-- Start: Header -->
        <header class="navbar navbar-fixed-top">

        </header>

        <!-- End: Header --> 
        <!-- Start: Main -->
        <div id="main"> 
            <!-- Start: Content -->
            <section id="content">
                <div id="topbar">
                    <ol class="breadcrumb">
                        <li><a href="/login/"><i class="fa fa-home"></i></a></li>
                        <li><a href="/login/">Voltar</a></li>
                    </ol>
                </div>
                <div class="container"> 
                    <?php echo $this->layout()->content; ?>
                </div>
            </section>
            <!-- End: Content --> 
        </div>
        <!-- End: Main --> 


    </body>
</html>