<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="pragma" content="no-cache">
        <meta http-equiv="Cache-control" content="no-cache">
        <meta http-equiv="cache-control" content="no-cache, must-revalidate">	
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php echo $this->headMeta(); ?> 
        <?php echo $this->headTitle(); ?>

        <!-- Font CSS  -->
        <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Open+Sans:400,600,700" />

        <!-- Core CSS  -->
        <link rel="stylesheet" type="text/css" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" />
        <link rel="stylesheet" type="text/css" href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" />
        <link rel="stylesheet" type="text/css" href="/fonts/glyphicons_pro/glyphicons.min.css" />


        <!-- Theme CSS -->

        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/theme.css') . "\n\r"; ?>  
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/pages.css') . "\n\r"; ?>  
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/plugins.css') . "\n\r"; ?>  
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/responsive.css') . "\n\r"; ?>  

        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/vendor/plugins/daterange/daterangepicker.css') . "\n\r"; ?>  



        <!-- Demonstration CSS -->
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/demo.css') . "\n\r"; ?>  

        <!-- Your Custom CSS -->
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/custom.css') . "\n\r"; ?>  

        <!-- Favicon -->
        <link rel="shortcut icon" href="/img/favicon.ico" />

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>
		    <style type="text/css">
        /* no exist  ----------- */
        @media only screen 
        and (min-device-width : 200px) 
        and (max-device-width : 319px) {
            /* Styles */
            #header-id{clear:both;position:relative; border:1px red solid;}
            #topbar{clear:both;position:relative;width:20%; display: none;}
            // #sidebar-search{position:relative}
            #topbar .breadcrumb{display: none;}

            .pull-left { width:30%}
            .pull-left .img-responsive{ width:100%}
            #header-right { width:35%}
            #dropdown-menu-login {width:80%; float:right !important;   }

            .container .panel {width:160px;}
			#mapper-location #mapa {width:150px; height:100px; border:2px red solid;}
			
			.panel-heading {min-height:100px;}
			#div_btn {display:table; float:left; width:100%; border:3px red solid;}
			#div_btn .popover-demo { float:right;clear:both;}
			#panel-login { width:140px;}
        }

        /* Smartphones (portrait and landscape) ----------- */
        @media only screen 
        and (min-device-width : 320px) 
        and (max-device-width : 480px) {
            /* Styles */
            #header-id{clear:both;position:relative;border:1px green solid;}
            #topbar{clear:both;position:relative;width:20%; display: none;}
            // #sidebar-search{position:relative}
            #topbar .breadcrumb{display: none;}

            .pull-left { width:30%}
            .pull-left .img-responsive{ width:100%}
            #header-right { width:35%}
            #dropdown-menu-login {width:80%; float:right !important;   }

            .container .panel {width:220px;}
			#mapper-location #mapa {width:160px; height:200px;  border:2px blue solid;}
			
			.panel-heading {min-height:100px;}
			#div_btn {display:table; float:left; width:100%; border:3px red solid;}
			#div_btn .popover-demo { float:right;clear:both;}
			#panel-login { width:270px;}
        }


        /* Smartphones (landscape) ----------- */
        @media only screen 
        and (min-width : 321px ) 
        and (max-width : 397px) {
            /* Styles */
            #header-id{ clear:both;position:relative;border:1px blue solid;}
            #topbar{ clear:both; position:relative;width:20%; display: none;}

            #topbar .breadcrumb{display: none;}

            .pull-left {width:30%}
            .pull-left .img-responsive{width:100%}
            #header-right { width:30%}
            #dropdown-menu-login { width:80%; float:right !important;   }

            .container .panel {width:200px;}
            .container .panel .btn-group { margin-left:  auto; margin-right:  auto; width: 50px; margin-top: 5px; clear:both;}
			
			#mapper-location #mapa {width:200px; height:200px;}
			
			.panel-heading{ min-height:90px;}
			#div_btn {display:none;}
			#div_btn .popover-demo { float:right;clear:both;}
			#panel-login{ border:1px green solid;}
			#panel-login { width:270px;}
        }


        @media only screen 
        and (min-width : 398px ) 
        and (max-width : 480px) {
            /* Styles */
            #header-id{ clear:both;position:relative;border:1px purple solid;}
            #topbar{ clear:both; position:relative;width:20%; display: none;}

            #topbar .breadcrumb{display: none;}

            .pull-left {width:30%}
            .pull-left .img-responsive{width:100%}
            #header-right { width:30%}
            #dropdown-menu-login { width:80%; float:right !important;   }

            .container .panel {width:280px;}
            .container .panel .btn-group { margin-left:  auto; margin-right:  auto; width: 50px; margin-top: 5px; clear:both;}
			#mapper-location #mapa {width:280px; height:220px;}
						
			#div_btn {display:none;}
			#div_btn .popover-demo { float:right;clear:both;}
			#panel-login { width:270px;}
        }


        /* Smartphones (portrait) ----------- */
        @media only screen 
        and (max-width : 320px) {
            /* Styles */
            #header-id{clear:both;position:relative;border:1px green solid;}
            #topbar{clear:both;position:relative;width:20%; display: none;}
            // #sidebar-search{position:relative}
            #topbar .breadcrumb{display: none;}

            .pull-left { width:20%}
            .pull-left .img-responsive{ width:100%}
            #header-right { width:30%;margin-right:10px;}
            #dropdown-menu-login {width:80%; float:right !important;   }

            #header-right { width:30%}
            #dropdown-menu-login { width:175px; float:left; margin-left: -120px;}
			#mapper-location #mapa {width:200px; height:250px;border:3px blue solid;float:left; margin-left: -20px;}
	
			.panel-title { font-size:10px;}
			.panel-heading{ min-height:80px;}
			#ul-administracao {display:none;}
			#div_btn {display:none;}
			#div_btn .popover-demo { float:right;clear:both;}
			
			#panel-login { width:200px;}
        }

        /* Neutro 1  ----------- */
        @media only screen 
        and (min-width : 480px) 
        and (max-width : 767px) {
            /* Styles */

            #header-id{clear:both;position:relative;}
            #topbar{clear:both;position:relative;width:30%; display: none;}
            // #sidebar-search{position:relative}
            #topbar .breadcrumb{display: none;}

            .pull-left { width:30%}
            .pull-left .img-responsive{ width:100%}
            #header-right { width:15%}
            #dropdown-menu-login {width:270px; float:left; margin-left: -220px;}

			#mapper-location #mapa {width:390px; height:350px;}
			
			
			#div_btn {display:none;}
			#div_btn .popover-demo { float:right;clear:both;}			
        }

        /* Neutro 2  ----------- */
        @media only screen 
        and (min-width : 768px) 
        and (max-width : 998px) {
            /* Styles */

            #header-id{ clear:both;position:relative;}
            #topbar{ clear:both;position:relative;width:30%; display: none;}
            // #sidebar-search{position:relative}
            #topbar .breadcrumb{display: none;}

            .pull-left { width:30%}
            .pull-left .img-responsive{ width:100%}
            #header-right { width:10%}
            #dropdown-menu-login { width:270px; float:left; margin-left: -220px;}

			#mapper-location #mapa {width:640px; height:350px;}
        }

        /* Neutro 3  ----------- */
        @media only screen 
        and (min-width : 999px) 
        and (max-width : 1223px) {
            /* Styles */

            #header-id{clear:both;position:relative;}
            #topbar{clear:both;position:relative;width:30%; display: none;}
            // #sidebar-search{position:relative}
            #topbar .breadcrumb{display: none;}

            .pull-left { width:30%}
            .pull-left .img-responsive{ width:100%}
            #header-right { width:7%}
            #dropdown-menu-login { width:270px; float:left; margin-left: -220px;}

			#mapper-location #mapa {width:890px; height:500px;}
        }


        /* iPads (landscape) ----------- */
        @media only screen 
        and (min-device-width : 768px) 
        and (max-device-width : 1024px) 
        and (orientation : landscape) {
            /* Styles */
            #header-id{border:1px yellow solid;clear:both;position:relative;}
            #topbar{border:1px yellow solid;clear:both;position:relative;width:30%; display: none;}
            // #sidebar-search{position:relative}
            #topbar .breadcrumb{display: none;}

            .pull-left { border: 2px yellow solid; width:30%}
            .pull-left .img-responsive{ border: 2px yellow solid; width:100%}
            #header-right { border: 2px yellow solid; width:30%}
            #dropdown-menu-login {border: 2px yellow solid; width:80%; float:right !important;   }
        }

        /* iPads (portrait) ----------- */
        @media only screen 
        and (min-device-width : 768px) 
        and (max-device-width : 1024px) 
        and (orientation : portrait) {
            /* Styles */
        }

        /* Desktops and laptops ----------- */
        @media only screen 
        and (min-width : 1224px) {
            /* Styles */

            #header-id{clear:both;position:relative;}
            #topbar{clear:both;position:relative;width:30%; display: none;}
            // #sidebar-search{position:relative}
            #topbar .breadcrumb{display: none;}

            .pull-left { width:30%}
            .pull-left .img-responsive{ width:100%}
            #header-right { width:8%}
            #dropdown-menu-login {width:300px; float:left; margin-left: -220px;}
				
			#mapper-location #mapa {width:1024px; height:500px;}

        }

        /* Large screens ----------- */
        @media only screen 
        and (min-width : 1824px) {
            /* Styles */
            #header-id{ clear:both;position:relative;}
            #topbar{ clear:both;position:relative;width:30%; display: none;}
            // #sidebar-search{position:relative}
            #topbar .breadcrumb{display: none;}

            .pull-left { width:30%}
            .pull-left .img-responsive{ width:100%}
            #header-right {width:10%}
            #dropdown-menu-login {width:370px; float:left; margin-left: -270px;}


        }

        /* iPhone 4 ----------- */
        @media
        only screen and (-webkit-min-device-pixel-ratio : 1.5),
        only screen and (min-device-pixel-ratio : 1.5) {
            /* Styles */
        }

    </style>

	
    <body class="login-page">
        <!-- Start: Main -->
        <div id="main">
            <div class="container">
                <?php echo $this->layout()->content; ?>

            </div>
        </div>
        <!-- End: Main --> 


        <!-- Core Javascript - via CDN --> 
        <script src="/js/jquery.min.js"></script> 
        <script src="/js/jquery-ui.min.js"></script> 
        <script src="/js/bootstrap.min.js"></script> 
        <!-- Theme Javascript --> 
        <script type="text/javascript">
            $(document).ready(function() {
                // Init Theme Core 	  
                Core.init();
                $('#retorno').hide();
                $('#loading').hide();
            });
        </script>
        <script type="text/javascript" src="/vendor/plugins/daterange/moment.min.js"></script> 
        <script type="text/javascript" src="/vendor/plugins/daterange/daterangepicker.js"></script> 
        <script type="text/javascript" src="/js/uniform.min.js"></script> 
        <script type="text/javascript" src="/js/main.js"></script>
        <script type="text/javascript" src="/js/custom.js"></script> 
        <script type="text/javascript"  src="/js/pedidos/pesquisar.js"></script>
        <script type="text/javascript"  src="/js/filiais/imprime.js"></script>
    </body>
</html>
