<form role="form" class="form-horizontal" id="signupForm">
    <div class="col-md-3 col-lg-4">
        <div class="row">
            <div class="col-md-11">
                <div class="panel profile-panel">
                    <div class="panel-heading">
                        <div class="panel-title"> <i class="fa fa-user"></i> Usuário -</div>
                        <span class="panel-title-sm pull-left text-success" style="color: #7ec35d; padding-left: 7px; padding-top: 2px;"> Online</span>
                        <div class="panel-btns pull-right margin-left">
                            <div class="btn-group">
                                <p class="popover-demo">
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="panel-body" style="z-index: 0;">

                        <div data-name="myimage" data-provides="fileupload" class="fileupload fileupload-exists">
                            <input type="hidden" value="" name="myimage">
                            <div id="new">
                                <div id="img_profile" style="max-width: 300px; max-height: 260px; line-height: 34px;" class="fileupload-preview fileupload-exists thumbnail"> </div>
                            </div>
                            <div>
                                <div class="btn-group">
                                    <button class="btn btn-primary btn-gradient" type="button" id="pesq_img">Imagem</button>
                                    <input name="img_perfil" id="img_perfil" style="display: none;" id="file_upload_perfil" class="btn btn-primary btn-gradient"  value="imagem" type="file">
                                </div>
                                <input style="display: none;" id="file_upload_perfil" class="btn btn-primary btn-gradient"  value="imagem" type="file">
                            </div>
                        </div>
                    </div>

                    <div class="panel-footer">
                        <div class="row">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




    <div class="col-md-6">
        <div class="row">
            <div class="col-md-12">
                <div class="panel">
                    <div class="panel-heading">
                        <div class="panel-title"> <i class="fa fa-pencil"></i> Perfil </div>
                    </div>
                    <div class="panel-body">

                        <div class="form-group">
                            <label class="col-lg-4 text-right"> Usuário <div style="float: right; margin-left: 5px; color:red">*</div> </label>
                            <div class="col-lg-8">
                                <input type="text" required="" placeholder="Username" name="username" class="form-control" value="" id="username_form">
                                <label class="error" id="username_error" for="username" style="display:none;">Please enter a username</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label" for="inputStandard"> Nome <div style="float: right; margin-left: 5px; color:red">*</div> </label>
                            <div class="col-lg-8">
                                <input type="text" id="nomeCompleto_form" placeholder="Nome completo"  name="nomeCompleto" value="" class="form-control">
                                <label class="error" id="nome_error" for="username" style="display:none;">Please enter a username</label>
                            </div>
                        </div>


                        <div class="form-group" style="display: none;" id="result_uf">

                        </div>


                        <div class="form-group" style="display: none;" id="result_cidade">

                        </div>

                        <div class="form-group">
                            <label class="col-lg-4 control-label" for="inputPassword">Password<div style="float: right; margin-left: 5px; color:red">*</div> </label>
                            <div class="col-lg-8">
                                <input type="password" placeholder="Password" name="password" value="" class="form-control" required="" id="password_form">
                                <label class="error" id="password_error" for="username" style="display:none;">Please enter a username</label>
                            </div>
                        </div>

                        <div class="form-group" style="display:none;">
                            <label class="col-lg-4 control-label" for="inputPassword">Confirma Password <div style="float: right; margin-left: 5px; color:red">*</div> </label>
                            <div class="col-lg-8">
                                <input type="password" name="confir_password" placeholder="Confirm Password" value="" class="form-control" id="confirm_password_form">
                                <label class="error" id="confirm_password_error" for="username" style="display:none;">Please enter a username</label>
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-lg-4 control-label" for="focusedInput"> E-mail <div style="float: right; margin-left: 5px; color:red">*</div> </label>
                            <div class="col-lg-8">
                                <input type="text" name="email" placeholder="E-mail" value="" class="form-control"  id="email_form">
                                <label id="email_error" class="error" for="username" style="display:none;">Please enter a username</label>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-3 control-label" for="focusedInput"> Descrição </label>
                            <div class="col-lg-9">
                                <textarea name="descricao" placeholder="Descrição" id="focusedInput" class="form-control"></textarea>
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="col-lg-6">

                                <button value="Atualizar Perfil" class="btn btn-primary btn-gradient submitFrom" id="submitFrom" data-toggle="modal" data-target="#submitModal">
                                    <i class="glyphicons glyphicons-search"></i>
                                    <label> Salvar </label>
                                </button>
                            </div>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
</form>


<div class="modal fade" id="submitModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title">Itens Encontrados</h4>
            </div>

            <div class="modal-body" id="getTableIntes">
                <div id="totalr"></div>
                <div>
                    <ul id="paginacao" class="pagination margin-bottom"></ul>
                </div>
                <table border="1" class="table tabs-below dataTable" id="Itens_select">
                    <thead>
                    </thead>
                    <tbody></tbody>
                </table>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    Fechar
                </button>
            </div>
        </div>
    </div>
</div>


<style>
    #defaultModal {
        z-index: 9999999;
    }
    table.jQuery tr {
        background-color: #b7cebd !important;
    }
    table.jQuery tr.even {
        background-color: #b7cebd !important;
    }
    table.jQuery tr.hover {
        background-color: #b7cebd !important;
    }
    table.jQuery tr.even.hover {
        background-color: #5E740B !important;
    }

    table.css thead th {
        background-color: #bbb !important;
    }
    table.css tfoot td {
        background-color: #f5f5f5 !important;
    }
    table.css tr:nth-child(even) {
        background-color: #fff !important;
    }
    table.css tr:nth-child(odd) {
        background-color: #f5f5f5 !important;
    }
    table.css tr:nth-child(even):hover {
        background-color: #1c94c4 !important;
    }
    table.css tr:nth-child(odd):hover {
        background-color: #39b3d7 !important;
    }
    table.cabec th {
        border: 1px solid #000 !important
    }
</style>  




<link rel="stylesheet" href="/vendor/plugins/jqueryupload/css/jquery.fileupload.css" />
<link rel="stylesheet" href="/vendor/plugins/jqueryupload/css/jquery.fileupload-ui.css" />

<script type="text/javascript" src="vendor/plugins/validate/jquery.validate.js"></script> 
<script type="text/javascript" src="vendor/plugins/tags/tagmanager.js"></script> 
<script type="text/javascript" src="vendor/plugins/formswitch/js/bootstrap-switch.min.js"></script> 

<script type="text/javascript" src="/vendor/bootstrap/fileupload/fileupload.js"></script> 


<script type="text/javascript" src="/js/login/cadastrar.js"></script>